-- This file initializes model provider data. No manual execution is required; it runs automatically when the project starts.
-- --------------------------------------------------------
-- Initialize model provider data
DELETE FROM `ai_model_provider`;
INSERT INTO `ai_model_provider` (`id`, `model_type`, `provider_code`, `name`, `fields`, `sort`, `creator`, `create_date`, `updater`, `update_date`) VALUES
-- VAD model providers
('SYSTEM_VAD_SileroVAD', 'VAD', 'silero', 'SileroVAD Voice Activity Detection', '[{"key":"threshold","label":"Detection Threshold","type":"number"},{"key":"model_dir","label":"Model Directory","type":"string"},{"key":"min_silence_duration_ms","label":"Minimum Silence Duration","type":"number"}]', 1, 1, NOW(), 1, NOW()),

-- ASR model providers
('SYSTEM_ASR_FunASR', 'ASR', 'fun_local', 'FunASR Speech Recognition', '[{"key":"model_dir","label":"Model Directory","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_ASR_SherpaASR', 'ASR', 'sherpa_onnx_local', 'SherpaASR Speech Recognition', '[{"key":"model_dir","label":"Model Directory","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_ASR_DoubaoASR', 'ASR', 'doubao', 'Volcano Engine Speech Recognition', '[{"key":"appid","label":"App ID","type":"string"},{"key":"access_token","label":"Access Token","type":"string"},{"key":"cluster","label":"Cluster","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"}]', 3, 1, NOW(), 1, NOW()),

-- LLM model providers
('SYSTEM_LLM_openai', 'LLM', 'openai', 'OpenAI Interface', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"model_name","label":"Model Name","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"temperature","label":"Temperature","type":"number"},{"key":"max_tokens","label":"Max Tokens","type":"number"},{"key":"top_p","label":"top_p Value","type":"number"},{"key":"top_k","label":"top_k Value","type":"number"},{"key":"frequency_penalty","label":"Frequency Penalty","type":"number"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_AliBL', 'LLM', 'AliBL', 'Alibaba Bailian Interface', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"app_id","label":"App ID","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"is_no_prompt","label":"Disable Local Prompt","type":"boolean"},{"key":"ali_memory_id","label":"Memory ID","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_ollama', 'LLM', 'ollama', 'Ollama Interface', '[{"key":"model_name","label":"Model Name","type":"string"},{"key":"base_url","label":"Service Address","type":"string"}]', 3, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_dify', 'LLM', 'dify', 'Dify Interface', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"mode","label":"Conversation Mode","type":"string"}]', 4, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_gemini', 'LLM', 'gemini', 'Gemini Interface', '[{"key":"api_key","label":"API Key","type":"string"},{"key":"model_name","label":"Model Name","type":"string"},{"key":"http_proxy","label":"HTTP Proxy","type":"string"},{"key":"https_proxy","label":"HTTPS Proxy","type":"string"}]', 5, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_coze', 'LLM', 'coze', 'Coze Interface', '[{"key":"bot_id","label":"Bot ID","type":"string"},{"key":"user_id","label":"User ID","type":"string"},{"key":"personal_access_token","label":"Personal Access Token","type":"string"}]', 6, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_fastgpt', 'LLM', 'fastgpt', 'FastGPT Interface', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"variables","label":"Variables","type":"dict","dict_name":"variables"}]', 7, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_xinference', 'LLM', 'xinference', 'Xinference Interface', '[{"key":"model_name","label":"Model Name","type":"string"},{"key":"base_url","label":"Service Address","type":"string"}]', 8, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_doubao', 'LLM', 'doubao', 'Volcano Engine LLM', '[{"key":"base_url","label":"Base URL","type":"string"},{"key":"model_name","label":"Model Name","type":"string"},{"key":"api_key","label":"API Key","type":"string"}]', 9, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_chatglm', 'LLM', 'chatglm', 'ChatGLM Interface', '[{"key":"model_name","label":"Model Name","type":"string"},{"key":"url","label":"Service Address","type":"string"},{"key":"api_key","label":"API Key","type":"string"}]', 10, 1, NOW(), 1, NOW()),

-- TTS model providers
('SYSTEM_TTS_edge', 'TTS', 'edge', 'Edge TTS', '[{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_doubao', 'TTS', 'doubao', 'Volcano Engine TTS', '[{"key":"api_url","label":"API Address","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"authorization","label":"Authorization","type":"string"},{"key":"appid","label":"App ID","type":"string"},{"key":"access_token","label":"Access Token","type":"string"},{"key":"cluster","label":"Cluster","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_siliconflow', 'TTS', 'siliconflow', 'SiliconFlow TTS', '[{"key":"model","label":"Model","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"access_token","label":"Access Token","type":"string"},{"key":"response_format","label":"Response Format","type":"string"}]', 3, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_cozecn', 'TTS', 'cozecn', 'COZECN TTS', '[{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"access_token","label":"Access Token","type":"string"},{"key":"response_format","label":"Response Format","type":"string"}]', 4, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_fishspeech', 'TTS', 'fishspeech', 'FishSpeech TTS', '[{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"response_format","label":"Response Format","type":"string"},{"key":"reference_id","label":"Reference ID","type":"string"},{"key":"reference_audio","label":"Reference Audio","type":"dict","dict_name":"reference_audio"},{"key":"reference_text","label":"Reference Text","type":"dict","dict_name":"reference_text"},{"key":"normalize","label":"Normalize","type":"boolean"},{"key":"max_new_tokens","label":"Max New Tokens","type":"number"},{"key":"chunk_length","label":"Chunk Length","type":"number"},{"key":"top_p","label":"top_p Value","type":"number"},{"key":"repetition_penalty","label":"Repetition Penalty","type":"number"},{"key":"temperature","label":"Temperature","type":"number"},{"key":"streaming","label":"Streaming","type":"boolean"},{"key":"use_memory_cache","label":"Use Memory Cache","type":"string"},{"key":"seed","label":"Seed","type":"number"},{"key":"channels","label":"Channels","type":"number"},{"key":"rate","label":"Sample Rate","type":"number"},{"key":"api_key","label":"API Key","type":"string"},{"key":"api_url","label":"API Address","type":"string"}]', 5, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gpt_sovits_v2', 'TTS', 'gpt_sovits_v2', 'GPT-SoVITS V2', '[{"key":"url","label":"Service Address","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"text_lang","label":"Text Language","type":"string"},{"key":"ref_audio_path","label":"Reference Audio Path","type":"string"},{"key":"prompt_text","label":"Prompt Text","type":"string"},{"key":"prompt_lang","label":"Prompt Language","type":"string"},{"key":"top_k","label":"top_k Value","type":"number"},{"key":"top_p","label":"top_p Value","type":"number"},{"key":"temperature","label":"Temperature","type":"number"},{"key":"text_split_method","label":"Text Split Method","type":"string"},{"key":"batch_size","label":"Batch Size","type":"number"},{"key":"batch_threshold","label":"Batch Threshold","type":"number"},{"key":"split_bucket","label":"Split Bucket","type":"boolean"},{"key":"return_fragment","label":"Return Fragment","type":"boolean"},{"key":"speed_factor","label":"Speed Factor","type":"number"},{"key":"streaming_mode","label":"Streaming Mode","type":"boolean"},{"key":"seed","label":"Seed","type":"number"},{"key":"parallel_infer","label":"Parallel Inference","type":"boolean"},{"key":"repetition_penalty","label":"Repetition Penalty","type":"number"},{"key":"aux_ref_audio_paths","label":"Auxiliary Reference Audio Paths","type":"dict","dict_name":"aux_ref_audio_paths"}]', 6, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gpt_sovits_v3', 'TTS', 'gpt_sovits_v3', 'GPT-SoVITS V3', '[{"key":"url","label":"Service Address","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"text_language","label":"Text Language","type":"string"},{"key":"refer_wav_path","label":"Reference Audio Path","type":"string"},{"key":"prompt_language","label":"Prompt Language","type":"string"},{"key":"prompt_text","label":"Prompt Text","type":"string"},{"key":"top_k","label":"top_k Value","type":"number"},{"key":"top_p","label":"top_p Value","type":"number"},{"key":"temperature","label":"Temperature","type":"number"},{"key":"cut_punc","label":"Split Punctuation","type":"string"},{"key":"speed","label":"Speed","type":"number"},{"key":"inp_refs","label":"Input References","type":"dict","dict_name":"inp_refs"},{"key":"sample_steps","label":"Sample Steps","type":"number"},{"key":"if_sr","label":"Use SR","type":"boolean"}]', 7, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_minimax', 'TTS', 'minimax', 'Minimax TTS', '[{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"group_id","label":"Group ID","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"model","label":"Model","type":"string"},{"key":"voice_id","label":"Voice ID","type":"string"}]', 8, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_aliyun', 'TTS', 'aliyun', 'Alibaba Cloud TTS', '[{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"appkey","label":"App Key","type":"string"},{"key":"token","label":"Access Token","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"access_key_id","label":"Access Key ID","type":"string"},{"key":"access_key_secret","label":"Access Key Secret","type":"string"}]', 9, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_ttson', 'TTS', 'ttson', 'ACGNTTS', '[{"key":"token","label":"Access Token","type":"string"},{"key":"voice_id","label":"Voice ID","type":"string"},{"key":"speed_factor","label":"Speed Factor","type":"number"},{"key":"pitch_factor","label":"Pitch Factor","type":"number"},{"key":"volume_change_dB","label":"Volume Change","type":"number"},{"key":"to_lang","label":"Target Language","type":"string"},{"key":"url","label":"Service Address","type":"string"},{"key":"format","label":"Format","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"emotion","label":"Emotion","type":"number"}]', 10, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_openai', 'TTS', 'openai', 'OpenAI TTS', '[{"key":"api_key","label":"API Key","type":"string"},{"key":"api_url","label":"API Address","type":"string"},{"key":"model","label":"Model","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"speed","label":"Speed","type":"number"},{"key":"output_dir","label":"Output Directory","type":"string"}]', 11, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_custom', 'TTS', 'custom', 'Custom TTS', '[{"key":"url","label":"Service Address","type":"string"},{"key":"params","label":"Request Parameters","type":"dict","dict_name":"params"},{"key":"headers","label":"Request Headers","type":"dict","dict_name":"headers"},{"key":"format","label":"Audio Format","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"}]', 12, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_302ai', 'TTS', '302ai', '302AI TTS', '[{"key":"api_url","label":"API Address","type":"string"},{"key":"authorization","label":"Authorization","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"access_token","label":"Access Token","type":"string"}]', 13, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gizwits', 'TTS', 'gizwits', 'Gizwits TTS', '[{"key":"api_url","label":"API Address","type":"string"},{"key":"authorization","label":"Authorization","type":"string"},{"key":"voice","label":"Voice","type":"string"},{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"access_token","label":"Access Token","type":"string"}]', 14, 1, NOW(), 1, NOW()),

-- Memory model providers
('SYSTEM_Memory_mem0ai', 'Memory', 'mem0ai', 'Mem0AI Memory', '[{"key":"api_key","label":"API Key","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_Memory_nomem', 'Memory', 'nomem', 'No Memory', '[]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_Memory_mem_local_short', 'Memory', 'mem_local_short', 'Local Short-Term Memory', '[]', 3, 1, NOW(), 1, NOW()),

-- Intent model providers
('SYSTEM_Intent_nointent', 'Intent', 'nointent', 'No Intent Recognition', '[]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_Intent_intent_llm', 'Intent', 'intent_llm', 'LLM Intent Recognition', '[{"key":"llm","label":"LLM Model","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_Intent_function_call', 'Intent', 'function_call', 'Function Call Intent Recognition', '[{"key":"functions","label":"Function List","type":"dict","dict_name":"functions"}]', 3, 1, NOW(), 1, NOW());
